services:
  db:
    image: postgres:16-alpine
    container_name: notaki_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notaki
      POSTGRES_USER: notaki
      POSTGRES_PASSWORD: notaki
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: ./back
    container_name: notaki_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: notaki
      DB_USERNAME: notaki
      DB_PASSWORD: notaki
      FRONT_URL: http://localhost:3000
    ports:
      - "8080:8080"

volumes:
  postgres_data:
